use_frameworks!

platform :ios, '9.0'

target 'XLRequestDebug_Example' do
  pod 'XLRequestDebug', :path => '../'
  pod 'AFNetworking', '~> 4.0'

  target 'XLRequestDebug_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
